/* Module that exports functions to load and lookup ground truth data from Themis */
import { parseSparqlResults } from './queryTools/parseSparqlResults';
import mandatarissenSparqlResult from '../data/mandatarissen.json';
const mandatarissen = parseSparqlResults(mandatarissenSparqlResult);

/*
data in mandatarissen.json was generated by the following query:

PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX persoon: <https://data.vlaanderen.be/ns/persoon#>
PREFIX g: <https://data.vlaanderen.be/ns/generiek#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT ?legislatuur ?legislatuurLabel ?regering  ?van ?tot ?regeringsLabel ?mandataris ?voornaam ?familienaam ?bestuursfunctieLabel ?titel ?rangorde ?start ?einde ?persoon ?mandaat ?bestuursfunctie WHERE {
  ?legislatuur g:isTijdspecialisatieVan <http://themis.vlaanderen.be/id/bestuursorgaan/7f2c82aa-75ac-40f8-a6c3-9fe539163025> .
  ?legislatuur skos:prefLabel ?legislatuurLabel .
  ?regering g:isTijdspecialisatieVan ?legislatuur .
  ?regering skos:prefLabel ?regeringsLabel .
  ?regering prov:hadMember ?mandataris .
  ?regering prov:qualifiedGeneration ?creatie .
  ?creatie prov:atTime ?van .
  OPTIONAL {
    ?regering prov:qualifiedInvalidation ?opheffing .
    ?opheffing prov:atTime ?tot
  } .
  OPTIONAL { ?mandataris dcterms:title ?titel } .
  ?mandataris mandaat:start ?start .
  OPTIONAL { ?mandataris mandaat:einde ?einde } .
  OPTIONAL { ?mandataris mandaat:rangorde ?rangorde } .
  ?mandataris org:holds ?mandaat .
  ?mandaat org:role ?bestuursfunctie .
  ?bestuursfunctie skos:prefLabel ?bestuursfunctieLabel .
  ?mandataris mandaat:isBestuurlijkeAliasVan ?persoon .
  ?persoon persoon:gebruikteVoornaam ?voornaam .
  ?persoon foaf:familyName ?familienaam .
} ORDER BY ?start ?einde ?rangorde ?bestuursfunctieLabel
*/


/* The SPARQL results JSON format isn't exactly ideal to perform lookups,
so we re-shape the data to a more convenient format for what we need */
let regeringsData = {};
const createLookupDatasets = function () {
  // create a set of government legislatures, with a property containing each of their compositions, with the key being composed of the start date in DD-MM-YYY format.
  // These start dates also exist in Kaleidos for mandatarissen, and should make it easy to narrow down the set of possible matches
  regeringsData = {
    meta: {
      // some basic stats about the data
      aantalMandatarissen: 0,
      aantalSamenstellingen: 0
    },
    regeringen: {}
  };
  for (const mandataris of mandatarissen) {
    regeringsData.meta.aantalMandatarissen++
    // create the legislature if necessary
    let legislatuur = mandataris.legislatuur;
    if (!regeringsData.regeringen[legislatuur]) {
      regeringsData.regeringen[legislatuur] = {
        legislatuurLabel: mandataris.legislatuurLabel,
        regeringsLabel: mandataris.regeringsLabel,
        regering: mandataris.regering,
        van: mandataris.van,
        tot: mandataris.tot,
        samenstellingen: {},
        aantalSamenstellingen: 0
      };
    }
    // next create the composition if necessary
    let formattedStartDate = mandataris.start.substring(0,10); // get rid of any hours/minute/seconds suffixes we don't need
    if (!regeringsData.regeringen[legislatuur].samenstellingen[formattedStartDate]) {
      regeringsData.meta.aantalSamenstellingen++;
      regeringsData.regeringen[legislatuur].aantalSamenstellingen++;
      regeringsData.regeringen[legislatuur].samenstellingen[formattedStartDate] = {
        start: mandataris.start,
        einde: mandataris.einde,
        mandatarissen: []
      };
    }
    // now add the mandataris data
    const formattedMandataris = {
      mandataris: mandataris.mandataris,
      bestuursfunctieLabel: mandataris.bestuursfunctieLabel,
      rangorde: mandataris.rangorde,
      titel: mandataris.titel,
      persoon: mandataris.persoon,
      voornaam: mandataris.voornaam,
      familienaam: mandataris.familienaam,
      mandaat: mandataris.mandaat,
      bestuursfunctie: mandataris.bestuursfunctie,
      regeringsLabel: mandataris.regeringsLabel,
      regeringsDuurVan: mandataris.van,
      regeringsDuurTot: mandataris.tot,
      start: mandataris.start,
      einde: mandataris.einde
    };
    regeringsData.regeringen[legislatuur].samenstellingen[formattedStartDate].mandatarissen.push(formattedMandataris);
  }
};
createLookupDatasets();

export default regeringsData;
